Repository qaidjoharj53/Blood-Bridge, pull requests merged in 2023-10, with the labels that each got.

#4 Added a dark theme toggle button
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: hactoberfest-accepted

#2 Update README.md
  README.md
Labels: hactoberfest-accepted

#7 Update README.md
  README.md
Labels: hacktoberfest-accepted

#15 Added init database for docker + Cleaned up connection
  code/connection.php
  code/contact.php
  code/dashboard.php
  code/login.php
  code/register.php
  docker-compose.yml
  docker/mysql/Dockerfile
  docker/mysql/schema/00_registered_users.sql
Labels: hacktoberfest-accepted, backend

#17 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, hacktoberfest-accepted

#14 Organized php files into php folder
  .gitignore
  code/about.html
  code/canyoudonate.html
  code/index.html
  code/php/connection.php
  code/php/contact.php
  code/php/dashboard.php
  code/php/login.php
  code/php/logout.php
  code/php/register.php
  code/whydonate.html
Labels: hacktoberfest-accepted

#16 added contributing.md file
  CONTRIBUTING.md
Labels: documentation, hacktoberfest-accepted

#19 add contributors section in README.md file
  README.md
Labels: documentation, hacktoberfest-accepted
